### ISSUE TITLE
Paper for GI_Forum / AGIT Salzburg 2017

### ISSUE THREAD

**Issue by Murthy10** [geometalab/OSMDeepOD#116]

**Comment by das-g** [comment]
### call for papers
* [AGIT](http://agit.at/call) 
* [GI forum](http://www.gi-forum.org/call)
  * [informations for authors](http://www.gi-forum.org/author)

This year's motto "geospatial@online" fits our chosen topic nicely, I think. :smile:

### Previous work

1. [GEOSmart Innovation Initiative Day](https://www.geowebforum.ch/thread.php?postingID=3414#3414), November 2016 Bern
(see `OSM-Object-Detection_Presentation_Keller_v2.pptx` received by email)
2. [AGIT, Juli 2016](http://gispoint.de/gisopen-paper/3875-erkennung-von-fussgaengerstreifen-aus-orthophotos/agit.html?IDjournalTitle=5&tx_browser_pi1%5BIDedition%5D=5) Salzburg
(see `Keller_Erkennung_Fussgaengerstreifen_Vortrag.pptx` and `Keller_Erkennung_Fussgaengerstreifen_Fachartikel_v3.docx` received by email)

**Comment by Murthy10** [comment]
## Content
- overview
- process for success
- result (confusion matrix)
- visions, possibilities
- problems (imagery timestamp)

**Comment by das-g** [comment]
> - result (confusion matrix)

Maybe also a quick comparison between the new results and the ones from the Semester Thesis
