### ISSUE TITLE
set_from_config_parser: bbox_size and timeout

### ISSUE THREAD

**Issue by tufftuff93** [geometalab/OSMDeepOD#125]
This function try to load the parameters bbox_size and timeout from the REDIS section of src.role.config.ini

self.bbox_size = config.getint(section='REDIS', option='BboxSize', fallback=2000)
self.timeout = config.getint(section='REDIS', option='Timeout', fallback=5400)

but in the config.ini, theses arguments are in the JOB section
[JOB]
BboxSize = 2000
Timeout = 5400

**Comment by Murthy10** [comment]
@tufftuff93 You are right unfortunately if forgot to update the README.
Now I updated the documentation and cleaned up the code in the configuration.py.

It would be great if you do some tests and give me some feedback.
