### ISSUE TITLE
src/base/configuration.py: barrier vs DetectionBarrier

### ISSUE THREAD

**Issue by tufftuff93** [geometalab/OSMDeepOD#128]
configuration.py wants 'barrier' label configuration like {'option': 'barrier', 'fallback': '0.99'},

but in src/role/config.ini, the parameter name is DetectionBarrier
[...]
DetectionBarrier = 0.99
[...]

This give me an exception in method set_options of configuration.py
if not config_parser.has_option(section['section'], option['option']):
       raise Exception('Option {0} is not in section {1}!'.format(option['option'], section['section']))

**Comment by Murthy10** [comment]
Barrier = 0.99, is the right parameter in the config.ini (I already fixed this in the master branch)

It's to avoid redundant information, because the name of the section is DETECTION.

Thanks for the feedback.
