### ISSUE TITLE
consider adding 'openstreetmap' topic in the Github description

### ISSUE THREAD

**Issue by matkoniecz** [geometalab/OSMDeepOD#134]
I was looking at https://github.com/topics/openstreetmap and https://github.com/topics/osm (to check whatever my projects are correctly tagged) and it appears that `osm` version is used rarely and almost in all cases also `openstreetmap` tag is used. This project is one of two popular ones that have only `osm`.

**Comment by sfkeller** [comment]
Thanks! Added openstreetmap as tag there.
